spring.application.name=StudentApp
spring.datasource.url=jdbc:postgresql://localhost:5432/student
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=create

spring.liquibase.change-log= liquibase/changelog-master.yml

